[theme]
# ROKA Consulting Brand
primaryColor = "#1279BE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F8F8"
textColor = "#303030"
font = "sans serif"

[server]
maxUploadSize = 10
headless = true

[browser]
gatherUsageStats = false
